DEFAULT_EMBED_MODEL = "sentence-transformers/all-mpnet-base-v2"  
DEFAULT_SUM_MODEL = "google/flan-t5-small" 
MAX_INPUT_CHARS_SUMMARY = 1800  
DEFAULT_TOP_K = 5
TIME_BUDGET_SECONDS = 60
FINE_TUNE_ENABLED = True
FINE_TUNE_EXAMPLES_THRESHOLD = 10  
